### ISSUE TITLE
How to connect to local

### ISSUE THREAD

**Issue by saintplay** [galexrt/go-rcon#1] opened 2019-06-25 04:43 UTC
Hello,
I’m trying to connect to send commands to my own server, I’ve tried putting “localhost”, “127.0.0.1”, “0.0.0.0” but neither of those works.

**Comment by galexrt** [comment] 2020-04-16 15:54
Gameserver normally don't run on `127.0.0.1` / localhost.
Check on which IP address the gameserver is actually listening to be able to connect to it.
E.g., under linux `netstat -tulpn` and / or `ss -tulpn`.

***

Closing as not a bug.

**Closed as completed by galexrt** 2020-04-16 15:54 UTC
